config:
  properties:
    state: "GATEWAY SERVER DEVELOPMENT CONFIG"

server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: newsserver
          uri: lb://newsserver
          predicates:
            - Path=/news/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
